branch-defaults:
  master:
    environment: nfuse-env
global:
  application_name: Nfuse
  default_ec2_keyname: null
  default_platform: Ruby 2.0 (Puma)
  default_region: us-west-1
  profile: eb-cli
  sc: git
