branch-defaults:
  master:
    environment: Nfuse
global:
  application_name: Nfuse1.1
  default_ec2_keyname: Ted's Key Pair
  default_platform: Ruby 2.0 (Puma)
  default_region: us-west-1
  profile: eb-cli
  sc: git
