module NfuseBase
  class Timeline
    TWITTER_PAGINATION_COUNT   = 1
    INSTAGRAM_PAGINATION_COUNT = 1
    TUMBLR_PAGINATION_COUNT    = 1
    YOUTUBE_PAGINATION_COUNT   = 1
    GPLUS_PAGINATION_COUNT     = 1
    VIMEO_PAGINATION_COUNT     = 1
    FLICKR_PAGINATION_COUNT    = 1
  end
end
