# development:
#   bucket: elasticbeanstalk-us-west-1-519554470540
#   access_key_id: ENV["AWS_ACCESS_KEY_ID"]
#   secret_access_key: ENV["AWS_SECRET_KEY"]
#   host: 'aa1cee2z3awja3v.c97qscmi7euu.us-west-1.rds.amazonaws.com'
# test:
#   bucket: 'elasticbeanstalk-us-west-1-519554470540'
#   access_key_id: ENV["AWS_ACCESS_KEY_ID"]
#   secret_access_key: ENV["AWS_SECRET_KEY"]
# production:
#   bucket: 'elasticbeanstalk-us-west-1-519554470540'
#   access_key_id: ENV["AWS_ACCESS_KEY_ID"]
#   secret_access_key: ENV["AWS_SECRET_KEY"]