# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#   Page(id: integer, page_counter_cache: integer, page_name: string, thing_name: string, twitter_handle: string, 
	# youtube_handle: string, instagram_handle: string, facebook_handle: string, pinterest_handle: string, 
	# tumblr_handle: string, gplus_handle: string, metatag_title: string, description: text, 
	# page_avatar_file_name: string, page_avatar_content_type: string, page_avatar_file_size: integer, 
	# page_avatar_updated_at: datetime, page_category: string)


pages = Page.create([
	
	{page_name: 'wired', full_name: 'wired', twitter_handle: 'wired', youtube_handle: 'https://youtube.com/user/wired', instagram_handle: 'wired', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Wired | Discover Tech and The Future ', description: 'WIRED is where tomorrow is realized. Follow one feed with all wired social media.', page_category: 'Business, nerdish'},

	{page_name: 'NatGeo', full_name: 'National Geographic', twitter_handle: 'NatGeo', youtube_handle: 'https://www.youtube.com/user/NationalGeographic', instagram_handle: 'natgeo', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'National Geographic | Social Media | Nfuse.it', description: "Since 1888, we've traveled the Earth, sharing its amazing stories with new generations. Official Nfuse account of National Geographic.", page_category: 'Business, travel, animals'},

	{page_name: 'Time', full_name: 'Time Magazine', twitter_handle: 'TIME', youtube_handle: 'https://www.youtube.com/user/TimeMagazine', instagram_handle: 'time', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Time Magazine | Nfuse and Breaking Social News', description: 'Breaking news and current events from around the globe. Explore the latest post on Nfuse.', page_category: 'Business, news'},

	{page_name: 'Reddbull', full_name: 'Redbull', twitter_handle: 'redbull', youtube_handle: 'https://www.youtube.com/user/redbull', instagram_handle: 'redbull', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Redbull | The Wings of Social Media ', description: 'Redbull gives you more than wings, folow our feed and discover our latest psot on social media.', page_category: 'Business'},

	{page_name: 'Forbes', full_name: 'Forbes Magazine', twitter_handle: 'Forbes', youtube_handle: 'https://www.youtube.com/user/forbes', instagram_handle: 'forbes', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Forbes Magazine | Social Business Post and Advice', description: "Official Nfuse account of www.Forbes.com , homepage for the world's business leaders.", page_category: 'Business, news'},

	{page_name: 'Google', full_name: 'Google', twitter_handle: 'google', youtube_handle: 'https://www.youtube.com/user/Google', instagram_handle: 'google', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Google | Top Social Media for Google | Nfuse ', description: 'News and updates from Google on Nfuse feed and forum.', page_category: 'Business, nerdish'},

	{page_name: 'Tedtalks', full_name: 'Ted Talks', twitter_handle: 'TEDTalks', youtube_handle: 'https://www.youtube.com/user/TEDtalksDirector', instagram_handle: 'ted', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Tedtalks | One Place For All The Talks | Nfuse ', description: 'The official feed for www.TED.com . Ideas worth spreading. Join the conversation of Tedtalks forum.', page_category: 'Business, nerdish'},

	{page_name: 'Tesla', full_name: 'Tesla', twitter_handle: 'TeslaMotors', youtube_handle: 'https://www.youtube.com/user/TeslaMotors', instagram_handle: 'teslamotors', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Tesla | Break News! on www.nfuse.it', description: 'Always on Ludicrous mode. Maker of electric cars and renewable energy storage. Join the rEVolution!', page_category: 'Business'},

	{page_name: 'HBO', full_name: 'HBO', twitter_handle: 'HBO', youtube_handle: 'dhttps://www.youtube.com/user/HBOdrf', instagram_handle: 'hbo', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'HBO | Movies and Media on one platform ', description: "It's HBO... DUH", page_category: 'Business, tv'},

	{page_name: 'Marvel', full_name: 'Marvel', twitter_handle: 'Marvel', youtube_handle: 'https://www.youtube.com/user/MARVEL', instagram_handle: 'marvel', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Marvel | Social Websites In One Place | Nfuse ', description: 'The official Nfuse feed for Marvel Comics, Movies, Games and more.', page_category: 'Business, nerdish'},

{page_name: 'People', full_name: 'People Magazine', twitter_handle: 'people', youtube_handle: 'https://www.youtube.com/user/people', instagram_handle: 'peoplemag', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'People Magazine | Current Social News | Nfuse', description: 'www.PEOPLE.com is the No. 1 site for celebrity news! Discover all our social media in one place on Nfuse.', page_category: 'Business, celebrity, news'},

{page_name: 'SportsIllustrated', full_name: 'Sports Illustrated', twitter_handle: 'Sinow', youtube_handle: 'https://www.youtube.com/user/SportsIllustrated', instagram_handle: 'sportsillustrated', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Sports Illustrated | #1 Social Sports News', description: 'Breaking news, conversation and original reporting/insights on all sports. Join the forum conversation on Nfuse. ', page_category: 'Business, fashion'},

{page_name: 'Cosmopolitan', full_name: 'Cosmopolitan', twitter_handle: 'Cosmopolitan', youtube_handle: 'https://www.youtube.com/user/HelloStyleChannel', instagram_handle: 'cosmopolitan', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Cosmopolitan | Beauty and Trends | Nfuse', description: 'Follow Cosmopolitan on the worlds largest social mashup. Join our forum and discover what everyone is talking about. ', page_category: 'Business, fashion'},

{page_name: 'ESPN', full_name: 'ESPN', twitter_handle: 'espn', youtube_handle: 'https://www.youtube.com/user/ESPN', instagram_handle: 'espn', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'ESPN | Discover Top Sports On All Media', description: 'We talk about sports, sports, and well ... sports. Follow us and discover our latest social media post.', page_category: 'Business, tv, sports'},

{page_name: 'USweekly', full_name: 'US Weekly', twitter_handle: 'usweekly', youtube_handle: 'https://www.youtube.com/user/UsWeekly', instagram_handle: 'usweekly', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'US Weekly | Top Social Stories On Nfuse', description: 'Your trusted source for the latest celebrity news, photos, videos and more! Follow our feed and stay on top of everything. ', page_category: 'Business, news'},

{page_name: 'EW', full_name: 'Entertainment Weekly', twitter_handle: 'EW', youtube_handle: 'https://www.youtube.com/user/ew', instagram_handle: 'entertainmentweekly', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Entertainment Weekly | Everything In One Place', description: 'Pop culture news & opinion from Entertainment Weekly & www.EW.com. Join the conversation on our forum.', page_category: 'Business, news'},

{page_name: 'Newsweek', full_name: 'Newsweek', twitter_handle: 'Newsweek', youtube_handle: 'https://www.youtube.com/user/NewsweekVideo', instagram_handle: 'newsweek', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: "Newsweek's Social Media | Nfuse.it ", description: 'Newsweek brings you the top news and analysis on politics, science, technology, and culture.', page_category: 'Business, news'},
 
{page_name: 'Popsci', full_name: 'Popular Science', twitter_handle: 'PopSci', youtube_handle: 'https://www.youtube.com/user/Popscivideo', instagram_handle: 'popsci', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Popular Science and Tech Updates ', description: 'Science and technology news from the future! Follow all our social media in one place.', page_category: 'Business, news'},

{page_name: 'Vogue', full_name: 'Vogue', twitter_handle: 'voguemagazine', youtube_handle: 'https://www.youtube.com/user/Americanvogue', instagram_handle: 'voguemagazine', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Vogue | Beauty Tips and Top Fashion | Nfuse.it', description: 'The Official Nfuse Page of Vogue Magazine. Discover our latest post all in one place.', page_category: 'Business, fashion'},

{page_name: 'Bloomberg', full_name: 'Bloomberg Businessweek', twitter_handle: 'business', youtube_handle: 'https://www.youtube.com/user/Bloomberg', instagram_handle: 'bloomberg', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Bloomberg Businessweek | Business News| Nfuse', description: 'Connecting decision makers to a dynamic network of information, people and ideas. Connect with other Nfusers and discover more.', page_category: 'Business, news'},

{page_name: 'GQ', full_name: 'GQ Magazine', twitter_handle: 'GQMagazine', youtube_handle: 'https://www.youtube.com/user/GQVideos', instagram_handle: 'gq', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'GQ | Everything A Man Needs | Social Style ', description: 'The Official Nfuse Page of GQ Magazine. Discover our latest post all in one place.', page_category: 'Business, fashion, shopping'},

{page_name: 'HGTV', full_name: 'HGTV', twitter_handle: 'hgtv', youtube_handle: 'https://www.youtube.com/user/HGTV', instagram_handle: 'hgtv', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'HGTV | Design and Everything You Need To Know', description: 'The Official Nfuse Page of HGTV. Design and Everything you need to know on the Nfuse Feed. ', page_category: 'Business, tv'},

{page_name: 'Fortune', full_name: 'Fortune Magazine', twitter_handle: 'FortuneMagazine', youtube_handle: 'https://www.youtube.com/user/FortuneMagazineVideo', instagram_handle: 'fortunemag', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Fortune | Business and Lifestyle In One Place ', description: "FORTUNE's official Nfuse feed and forum. Here's what we're hearing, seeing, reading and writing. Visit us at www.fortune.com ", page_category: 'Business'},

{page_name: 'enews', full_name: 'E! News', twitter_handle: 'Enews', youtube_handle: 'https://www.youtube.com/user/enews', instagram_handle: 'enews', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'E! News | The Good The Bad and The Gossip', description: 'Get the latest, breaking celebrity news only on E! News. Discover the latest news on the Nfuse feed. Click to follow', page_category: 'Business, celebrity'},

{page_name: 'VictoriasSecret', full_name: 'Victoria’s Secret', twitter_handle: 'VictoriasSecret', youtube_handle: 'https://www.youtube.com/user/VICTORIASSECRET', instagram_handle: 'victoriassecret', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: "Victoria's Secret | Sexy Social Media Post", description: 'Welcome to the official feed for Victoria’s Secret, where Angels, Bombshells & the sexiest followers on Nfuse get their fix for everything VS.', page_category: 'Business, fashion'},

{page_name: 'CNN', full_name: 'CNN', twitter_handle: 'CNN', youtube_handle: 'https://www.youtube.com/user/CNN', instagram_handle: 'cnn', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'CNN | Breaking World News | Here First', description: 'It’s our job to #GoThere and tell the most difficult stories. Come with us!', page_category: 'Business, news, tv'},

{page_name: 'Showtime', full_name: 'Showtime', twitter_handle: 'SHO_Networks', youtube_handle: 'https://www.youtube.com/user/SHOWTIME', instagram_handle: 'showtime', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Showtime Shows and Movies | Nfuse.it ', description: 'The Official Nfuse Page for Showtime, join the conversation. ', page_category: 'Business, tv'},

{page_name: 'Syfy', full_name: 'Syfy', twitter_handle: 'SyfyTV', youtube_handle: 'https://www.youtube.com/user/syfy', instagram_handle: 'syfy', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Syfy | Science Fiction and Interesting Shows ', description: 'Not Sci-Fi, not SyFy, but @Syfy. Providing you with all the updates on your favorite shows, news, and events.', page_category: 'Business, nerdish'},

{page_name: 'Netflix', full_name: "Netflix", twitter_handle: 'netflix', youtube_handle: 'https://www.youtube.com/user/NewOnNetflix', instagram_handle: 'netflix', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Netflix | Top Movies and Show All On Nfuse ', description: 'The official feed for Netflix, follow all our social media in one place.', page_category: 'Business, tv'},

{page_name: 'BuzzFeed', full_name: 'BuzzFeed', twitter_handle: 'BuzzFeed', youtube_handle: 'https://www.youtube.com/user/BuzzFeedVideo', instagram_handle: 'buzzfeed', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Buzzfeed | Social Networks and Top Post', description: 'A news wire for the social web. ', page_category: 'Business'},

{page_name: 'Reddit', full_name: 'Reddit', twitter_handle: 'reddit', youtube_handle: 'https://www.youtube.com/user/reddit', instagram_handle: 'reddit', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Reddit | Top post shared from Reddit ', description: 'Reddit is a place for community, conversation, and connection with millions of users worldwide. Come for the cats. Stay for the community.', page_category: 'Business, news'},

{page_name: 'CollegeHumor', full_name: 'CollegeHumor', twitter_handle: 'CollegeHumor', youtube_handle: 'https://www.youtube.com/user/collegehumor', instagram_handle: 'collegehumor', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'College Humor | Discover The Funniest Post ', description: 'The official Nfuse feed for CollegeHumor.', page_category: 'Business'},

{page_name: 'Microsoft', full_name: 'Microsoft', twitter_handle: 'Microsoft', youtube_handle: 'https://www.youtube.com/user/Microsoft', instagram_handle: 'microsoft', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Microsoft | Best Social Media and top post ', description: 'The official Nfuse page for Microsoft consumer products and your source for major announcements and events.', page_category: 'Business, nerdish'},

{page_name: 'Nike', full_name: 'Nike', twitter_handle: 'Nike', youtube_handle: 'https://www.youtube.com/user/nike', instagram_handle: 'nike', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Nike | Just Do It On Nfuse | Explore Post ', description: '#justdoit, Discover all social post in one place. ', page_category: 'Business, fitness, fashion, sports'},

{page_name: 'IMDb', full_name: 'IMDb', twitter_handle: 'IMDb', youtube_handle: 'https://www.youtube.com/user/VideoIMDb', instagram_handle: 'imdb', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'IMDb | Movie Reviews on Nfuse ', description: 'The folks at IMDb talking about movies, TV and celebrities.', page_category: 'Business, tv'},

{page_name: 'Vevo', full_name: 'Vevo', twitter_handle: 'Vevo', youtube_handle: 'https://www.youtube.com/user/VEVO', instagram_handle: 'vevo', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Vevo | Find Great Music on top social platform', description: 'The official Nfuse page for Vevo.', page_category: 'Business'},

{page_name: 'Starwars', full_name: 'Starwars', twitter_handle: 'starwars', youtube_handle: 'https://www.youtube.com/user/starwars', instagram_handle: 'starwars', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Starwars | May The Force Be With Nfuse ', description: 'The official home of Star Wars on Nfuse. ', page_category: 'Business, nerdish'},

{page_name: 'NASA', full_name: 'NASA', twitter_handle: 'NASA', youtube_handle: 'https://www.youtube.com/user/NASAtelevision', instagram_handle: 'nasa', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Nasa | The Universe Is All Here | www.Nfuse.it', description: 'Explore the universe and discover our home planet with @NASA.', page_category: 'Business, nerdish'},

{page_name: 'Bravo', full_name: 'Bravo', twitter_handle: 'Bravotv', youtube_handle: 'https://www.youtube.com/user/BravoShows', instagram_handle: 'bravotv', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Bravo | Top Gossip and Social Post | Nfuse ', description: 'The official Nfuse page for Bravo.', page_category: 'Business'},

{page_name: 'MTV', full_name: 'MTV', twitter_handle: 'MTV', youtube_handle: 'https://www.youtube.com/user/MTV', instagram_handle: 'mtv', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'MTV | Music Post and Top TV | www.Nfuse.it', description: 'The official Nfuse page for MTV.', page_category: 'Business, music'},

{page_name: 'GolfDigest', full_name: 'Golf Digest', twitter_handle: 'GolfDigest', youtube_handle: 'https://www.youtube.com/user/GolfDigestMagazine', instagram_handle: 'golfdigest', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Golf Digest | Top Golf Post For Golf Lovers', description: 'The official Nfuse page for Golf Digest. ', page_category: 'Business, sports'},

{page_name: 'NBA', full_name: 'NBA', twitter_handle: 'NBA', youtube_handle: 'https://www.youtube.com/user/NBA', instagram_handle: 'nba', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'NBA | One Stop For All Things Basketball ', description: 'The official Nfuse page for NBA.', page_category: 'Business, sports'},

{page_name: 'NFL', full_name: 'NFL', twitter_handle: 'NFL', youtube_handle: 'https://www.youtube.com/user/NFL', instagram_handle: 'nfl', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'NFL | Top Football Post of 2016 | www.Nfuse.it', description: 'The official Nfuse page for NFL. ', page_category: 'Business, sports'},

{page_name: 'MLB', full_name: 'MLB', twitter_handle: 'MLB', youtube_handle: 'https://www.youtube.com/user/MLB', instagram_handle: 'mlb', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'MLB | Nfuse | The Social HUB', description: 'The official Nfuse page for MLB.', page_category: 'Business, sports'},

{page_name: 'NHL', full_name: 'NHL', twitter_handle: 'NHL', youtube_handle: 'https://www.youtube.com/user/NHLVideo', instagram_handle: 'nhl', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'NHL | Best 2016 Media in one please for Hockey', description: 'The official Nfuse page for NHL. ', page_category: 'Business, sports'},

{page_name: 'HISTORY', full_name: 'HISTORY Channel', twitter_handle: 'HISTORY', youtube_handle: 'https://www.youtube.com/user/historychannel', instagram_handle: 'history', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'History Channel and The Top Media Post', description: 'The official Nfuse page The History Channel. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, tv, nerdish'},

{page_name: 'FoodNetwork', full_name: 'Food Network', twitter_handle: 'FoodNetwork', youtube_handle: 'https://www.youtube.com/user/FoodNetworkTV', instagram_handle: 'foodnetwork', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Food Network | Yum That Looks Good | Nfuse', description: 'The official Nfuse page for The Food Network. Discover our feed with the top social post and join the conversation on the Nfuse forum. ', page_category: 'Business, tv, food'},

{page_name: 'USATODAY', full_name: 'USA Today', twitter_handle: 'USATODAY', youtube_handle: 'https://www.youtube.com/user/USATODAY', instagram_handle: 'usatoday', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'USA Today | Nfuse | Top Social Site ', description: 'The official Nfuse page for USA Today. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, news'},

{page_name: 'RalphLauren', full_name: 'Ralph Lauren', twitter_handle: 'RalphLauren', youtube_handle: 'https://www.youtube.com/user/RLTVralphlauren', instagram_handle: 'ralphlauren', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Ralph Lauren | Nfuse and Discover ', description: 'The official Nfuse page for Ralph Lauren. Discover our feed with the top social post and join the conversation on the Nfuse forum. ', page_category: 'Business, shopping, fashion'},

{page_name: 'ScienceChannel', full_name: 'Science Channel', twitter_handle: 'ScienceChannel', youtube_handle: 'https://www.youtube.com/user/ScienceChannel', instagram_handle: 'sciencechannel', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Science Channel | Dream Big on Nfuse ', description: 'The official Nfuse page for The Science Channel. Discover our feed with the top social post and join the conversation on the Nfuse forum. ', page_category: 'Business, tv, nerdish'},

{page_name: 'TLC', full_name: 'TLC', twitter_handle: 'TLC', youtube_handle: 'https://www.youtube.com/user/TLC', instagram_handle: 'tlc', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'TLC | Nfuse | The Number One Social Hub', description: 'The official Nfuse page for TLC. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, tv'},

{page_name: 'Inc', full_name: 'Inc Magazine', twitter_handle: 'Inc', youtube_handle: 'https://www.youtube.com/user/incmagazine', instagram_handle: 'incmagazine', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Inc. Experience the top business post from Inc.', description: 'The official Nfuse page for Inc. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, nerdish'},

{page_name: 'Makerbot', full_name: 'makerbot', twitter_handle: 'makerbot', youtube_handle: 'https://www.youtube.com/user/makerbot', instagram_handle: 'makerbot', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Makerbot 3d prints and top designs on Nfuse', description: 'The official Nfuse page for Makerbot. Discover our feed with the top social post and join the conversation on the Nfuse forum. ', page_category: 'Business, nerdish'},

{page_name: 'Olympics', full_name: 'Olympics', twitter_handle: 'Olympics', youtube_handle: 'https://www.youtube.com/user/olympic', instagram_handle: 'olympics', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Olympics best post from 2016 Olympics | Nfuse', description: 'The official Nfuse page for The Olympics. Discover our feed with the top social post and join the conversation on the Nfuse forum. ', page_category: 'Business, sports'},

{page_name: 'FIFA', full_name: 'FIFA', twitter_handle: 'FIFAWorldCup', youtube_handle: 'https://www.youtube.com/user/FIFATV', instagram_handle: 'fifaworldcup', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'FIFA Top Soccer Social Media on Nfuse ', description: 'The official Nfuse page for FIFA. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, sports'},

{page_name: 'TMZ', full_name: 'TMZ', twitter_handle: 'TMZ', youtube_handle: 'https://www.youtube.com/user/TMZ', instagram_handle: 'tmz_tv', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'TMZ | Social Media | Nfuse ', description: 'The official Nfuse page for TMZ. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, tv, celebrity'},

{page_name: 'Sony', full_name: 'Sony', twitter_handle: 'Sony', youtube_handle: 'https://www.youtube.com/user/sonyelectronics', instagram_handle: 'sony', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Sony | The future of gaming is here | www.nfuse.it', description: 'The official Nfuse page for Sony. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, nerdish'},

{page_name: 'Xbox', full_name: 'Xbox', twitter_handle: 'Xbox', youtube_handle: 'https://www.youtube.com/user/xbox', instagram_handle: 'xbox', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Xbox | Gaming News from the top gaming platform', description: 'The official Nfuse page for Xbox. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, nerdish'},

{page_name: 'Playstation', full_name: 'Playstation', twitter_handle: 'Playstation', youtube_handle: 'https://www.youtube.com/user/PlayStation', instagram_handle: 'playstation', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Playstation | Top gaming platform on Nfuse', description: 'The official Nfuse page for Playstation. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, nerdish'},
 
{page_name: 'Nordstrom', full_name: 'Nordstrom', twitter_handle: 'Nordstrom', youtube_handle: 'https://www.youtube.com/user/Nordstromcom', instagram_handle: 'nordstrom', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Nordstrom | Shop and Discover Top Fashion ', description: 'The official Nfuse page for Nordstrom. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, fashion, shopping'},

{page_name: 'Gucci', full_name: 'Gucci', twitter_handle: 'gucci', youtube_handle: 'https://www.youtube.com/user/gucciofficial', instagram_handle: 'gucci', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Gucci | Social Style and Post | www.nfuse.it ', description: 'The official Nfuse page for Gucci. Discover our feed with the top social post and join the conversation on the Nfuse forum. ', page_category: 'Business, fashion, shopping'},

{page_name: 'H&M', full_name: 'H&M', twitter_handle: 'hm', youtube_handle: 'https://www.youtube.com/user/hennesandmauritz', instagram_handle: 'hm', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'H&M | Fashion | Design | Media', description: 'The official Nfuse page for H&M. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, fashion, shopping'},

{page_name: 'Entrepreneur', full_name: 'Entrepreneur Magazine', twitter_handle: 'Entrepreneur', youtube_handle: 'https://www.youtube.com/user/EntrepreneurOnline', instagram_handle: 'entrepreneur', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Entrepreneur Magazine', description: 'The official Nfuse page for Entrepreneur Magazine. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business'},

{page_name: 'GE', full_name: 'General Electric', twitter_handle: 'generalelectric', youtube_handle: 'https://www.youtube.com/user/GE', instagram_handle: 'generalelectric', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'General Electric | Ground Breaking Design | Nfuse', description: 'The official Nfuse page for General Electric. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, nerdish'},

{page_name: 'TiffanyandCo', full_name: 'Tiffany & Co', twitter_handle: 'TiffanyandCo', youtube_handle: 'https://www.youtube.com/user/OfficialTiffanyAndCo', instagram_handle: 'tiffanyandco', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Tiffany & Co | Say Yes to Nfuse ', description: 'The official Nfuse page for Tiffany & CO. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, shopping'},

{page_name: 'Amazon', full_name: 'Amazon', twitter_handle: 'amazon', youtube_handle: 'https://www.youtube.com/user/amazon', instagram_handle: 'amazon', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Amazon | Top Social Media post about Amazon', description: 'The official Nfuse page for Amazon. Discover our feed with the top social post and join the conversation on the Nfuse forum. ', page_category: 'Business, shopping'},

{page_name: 'GAP', full_name: 'GAP', twitter_handle: 'Gap', youtube_handle: 'https://www.youtube.com/user/Gap', instagram_handle: 'gap', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'GAP | Style For Everyone | Style HUB', description: 'The official Nfuse page for GAP. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, shopping'},

{page_name: 'BananaRepublic', full_name: 'Banana Republic', twitter_handle: 'BananaRepublic', youtube_handle: 'https://www.youtube.com/user/bananarepublic', instagram_handle: 'bananarepublic', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Banana Republic | Fashion for the world | Nfuse ', description: 'The official Nfuse page for Banana Republic. Discover our feed with the top social post and join the conversation on the Nfuse forum. ', page_category: 'Business, shopping'},

{page_name: 'CalvinKlein', full_name: 'Calvin Klein', twitter_handle: 'CalvinKlein', youtube_handle: 'https://www.youtube.com/user/calvinklein', instagram_handle: 'calvinklein', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Calvin Klein | Historic and New Fashion on Nfuse ', description: 'The official Nfuse page for Calvin Klein. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, fashion, shopping'},

{page_name: 'IBM', full_name: 'IBM', twitter_handle: 'IBM', youtube_handle: 'https://www.youtube.com/user/IBM', instagram_handle: 'ibm', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'IBM | 2016 Computer Trends and Best Post ', description: 'The official Nfuse page for IBM. Discover our feed with the top social post and join the conversation on the Nfuse forum. ', page_category: 'Business, nerdish'},

{page_name: 'Playboy', full_name: 'Playboy', twitter_handle: 'Playboy', youtube_handle: 'https://www.youtube.com/user/playboy', instagram_handle: 'playboy', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Playboy | Sexy And Beautiful Woman on Nfuse ', description: 'The official Nfuse page for Playboy. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business'},

{page_name: 'UnderArmour', full_name: 'Under Armour', twitter_handle: 'UnderArmour', youtube_handle: 'https://www.youtube.com/user/underarmour', instagram_handle: 'underarmour', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Under Armour | Best fitness brand and social post', description: 'The official Nfuse page for Under Armour. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, fitness, sports'},

{page_name: 'Armani', full_name: 'Armani', twitter_handle: 'armani', youtube_handle: 'https://www.youtube.com/user/Armani', instagram_handle: 'armani', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Armani | How to look good in 2016 on Nfuse', description: 'The official Nfuse page for Armani. Discover our feed with the top social post and join the conversation on the Nfuse forum. ', page_category: 'Business, fashion, shopping'},

{page_name: 'Facebook', full_name: 'Facebook', twitter_handle: 'facebook', youtube_handle: 'https://www.youtube.com/user/theofficialfacebook', instagram_handle: 'facebook', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Facebook | Worlds Largest Network On Nfuse ', description: 'The official Nfuse page for Facebook. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business'},

{page_name: 'Burberry', full_name: 'Burberry', twitter_handle: 'Burberry', youtube_handle: 'https://www.youtube.com/user/Burberry', instagram_handle: 'burberry', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Burberry | NFUSING Fashion and top looks ', description: 'The official Nfuse page for Burberry. Discover our social feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, fashion, shopping'},

{page_name: 'Maxim', full_name: 'Maxim Magazine', twitter_handle: 'MaximMag', youtube_handle: 'https://www.youtube.com/user/videosbyMaxim', instagram_handle: 'maximmag', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Maxim | Sexy and Hot Social Media Post | Nfuse.it', description: 'The official Nfuse page for Maxim. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business'},

{page_name: 'FOXSports', full_name: 'FOX Sports', twitter_handle: 'FOXSports', youtube_handle: 'https://www.youtube.com/user/FoxSports', instagram_handle: 'foxsports', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Fox Sports | Sports recaps and post on Nfuse ', description: 'The official Nfuse page for Fox Sports. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, sports'},

{page_name: 'Elle', full_name: 'Elle Magazine', twitter_handle: 'ELLEmagazine', youtube_handle: 'https://www.youtube.com/user/ElleMagazine', instagram_handle: 'elleusa', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Elle | Free Network | Nfuse.it', description: 'The official Nfuse page for Elle. Discover our social feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business'},

{page_name: 'ABCNetwork', full_name: 'ABC Network', twitter_handle: 'ABCNetwork', youtube_handle: 'https://www.youtube.com/user/ABCNetwork', instagram_handle: 'abcnetwork', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'ABC | www.nfuse.it', description: 'The official Nfuse page for ABC. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, tv'},

{page_name: 'CNBC', full_name: 'CNBC', twitter_handle: 'CNBC', youtube_handle: 'https://www.youtube.com/user/cnbc', instagram_handle: 'cnbc', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'CNBC | On Nfuse', description: 'The official Nfuse page for CNBC. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, tv'},

{page_name: 'NBC', full_name: 'NBC', twitter_handle: 'nbc', youtube_handle: 'https://www.youtube.com/user/NBC', instagram_handle: 'nbctv', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'NBC | Nfuse.it | Free Social Network', description: 'The official Nfuse page for NBC. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, tv'},

{page_name: 'CBS', full_name: 'CBS', twitter_handle: 'cbs', youtube_handle: 'https://www.youtube.com/user/CBS', instagram_handle: 'cbstv', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'CBS | www.nfuse.it ', description: 'The official Nfuse page for CBS. Discover our social feed with the top social post and join the conversation on the Nfuse forum. ', page_category: 'Business, tv'},

{page_name: 'TheCW', full_name: 'The CW', twitter_handle: 'CW_network', youtube_handle: 'https://www.youtube.com/user/Cwtelevision', instagram_handle: 'thecw', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'The CW | Top CW shows and post on Nfuse ', description: 'The official Nfuse page for The CW. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, tv'},

{page_name: 'HUGOBOSS', full_name: 'Hugo Boss', twitter_handle: 'HUGOBOSS', youtube_handle: 'https://www.youtube.com/user/HUGOBOSSTV', instagram_handle: 'hugoboss', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Hugo Boss | Fashion for Men and Woman', description: 'The official Nfuse page for Hugo Boss. Discover our feed with the top social post and join the conversation on the Nfuse forum. ', page_category: 'Business, fashion'},

{page_name: 'CBSNews', full_name: 'CBS News', twitter_handle: 'CBSNews', youtube_handle: 'https://www.youtube.com/user/CBSNewsOnline', instagram_handle: 'cbsnews', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'CBS News | Best News Source on top socia post', description: 'The official Nfuse page for CBS News. Discover our feed with the top social post and join the conversation on the Nfuse forum. ', page_category: 'Business, news'},

{page_name: 'FoxNews', full_name: 'Fox News', twitter_handle: 'FoxNews', youtube_handle: 'https://www.youtube.com/user/FoxNewsChannel', instagram_handle: 'foxnews', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Fox News | Discover all your news on Nfuse', description: 'The official Nfuse page for Fox News. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, news'},

{page_name: 'NBCNews', full_name: 'NBC News', twitter_handle: 'NBCNews', youtube_handle: 'https://www.youtube.com/user/NBCNews', instagram_handle: 'nbcnews', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'NBC News | Breaking National News | www.nfuse.it', description: 'The official Nfuse page for NBC News. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, news'},

{page_name: 'ABCNews', full_name: 'ABC News', twitter_handle: 'ABC', youtube_handle: 'https://www.youtube.com/user/ABCNews', instagram_handle: 'abcnews', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'ABC News | Nfuse ', description: 'The official Nfuse page for NBC News. Discover our feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, news'},

{page_name: 'CBSSports', full_name: 'CBSSports', twitter_handle: 'CBSSports', youtube_handle: 'https://www.youtube.com/user/CBSSports', instagram_handle: 'cbssports', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'CBS Sports | Sport post from CBS Sport ', description: 'The official Nfuse page for CBS Sports. Discover our feed with the top social post and join the conversation on the Nfuse forum. ', page_category: 'Business, sports'},

{page_name: 'FOXtv', full_name: 'Fox', twitter_handle: 'FOXTV', youtube_handle: 'https://www.youtube.com/user/FoxBroadcasting', instagram_handle: 'foxtv', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Fox | Nfuse ', description: 'The official Nfuse page for Fox. Discover our feed with the top social post and join the conversation on the Nfuse forum. ', page_category: 'Business, tv'},

{page_name: 'VanityFair', full_name: 'Vanity Fair', twitter_handle: 'VanityFair', youtube_handle: 'https://www.youtube.com/user/VanityFairMagazine', instagram_handle: 'vanityfair', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Vanity Fair | Top Fashion and Social Media | Nfuse', description: 'The official Nfuse page for Vanity Fair. Discover our feed with the top social post and join the conversation on the Nfuse forum. ', page_category: 'Business, fashion'},

{page_name: 'Brides', full_name: 'Brides', twitter_handle: 'brides', youtube_handle: 'https://www.youtube.com/user/BridesMagazine', instagram_handle: 'brides', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Brides | Wedding designs and Advice | www.nfuse.it', description: 'The official Nfuse page for Brides. Discover our social feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, wedding'},

{page_name: 'Uber', full_name: 'Uber', twitter_handle: 'Uber', youtube_handle: 'https://www.youtube.com/user/UberWorldwide', instagram_handle: 'uber', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Uber | Industry and Company Post on Uber | Nfuse', description: 'The official Nfuse page for Uber. Discover our social feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, nerdish'},

{page_name: 'Forever21', full_name: 'Forever 21', twitter_handle: 'Forever21', youtube_handle: 'https://www.youtube.com/user/Forever21Inc', instagram_handle: 'forever21', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Forever 21 | Always fresh and top design post ', description: 'The official Nfuse page for Forever 21. Discover our social feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, shopping, fashion'},

{page_name: 'MLS', full_name: 'MLS', twitter_handle: 'MLS', youtube_handle: 'https://www.youtube.com/user/mls', instagram_handle: 'mls', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'MLS | Soccer post and top new on Nfuse', description: 'The official Nfuse page for MLS. Discover our social feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, sports'},

{page_name: 'UrbanOutfitters', full_name: 'Urban Outfitters', twitter_handle: 'UrbanOutfitters', youtube_handle: 'https://www.youtube.com/user/uotv', instagram_handle: 'urbanoutfitters', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Urban Outfitters | Stay Bold and Trend On', description: 'The official Nfuse page for Urban Outfitters. Discover our social feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, fashion, shopping'},

{page_name: 'Allure', full_name: 'Allure Magazine', twitter_handle: 'Allure_magazine', youtube_handle: 'https://www.youtube.com/user/AllureMagazine', instagram_handle: 'allure', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Allure | All Fashion in one place | www.nfuse.it', description: 'The official Nfuse page for Allure. Discover our social feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business, fashion'},

{page_name: 'Wmag', full_name: 'W Magazine', twitter_handle: 'wmag', youtube_handle: 'https://www.youtube.com/user/wmagazinedotcom', instagram_handle: 'wmag', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'W Magazine | Nfuse Fashion for W Magazine', description: 'The official Nfuse page for W Magazine. Discover our social feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business'},

{page_name: 'theScene', full_name: 'The Scene', twitter_handle: 'SCENE', youtube_handle: 'https://www.youtube.com/user/thesceneYT', instagram_handle: 'thescene', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'The Scene | Top Mash Up on the greatest social site', description: 'The official Nfuse page for The Scene. Discover our social feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business'}

# {page_name: 'YouTube', full_name: 'YouTube', twitter_handle: 'YouTube', youtube_handle: 'https://www.youtube.com/user/YouTube', instagram_handle: 'youtube', facebook_handle: nil, pinterest_handle: nil, tumblr_handle: nil, gplus_handle: nil, metatag_title: 'Youtube | Discover Top Videos and Social Media', description: 'The official Nfuse page for Youtube. Discover our social feed with the top social post and join the conversation on the Nfuse forum.', page_category: 'Business'}

	])
