class SearchesController < ApplicationController
	#This controls the searches
  def index
  	#This shows all the users that fit the search criteria
    if params[:search]
      @users = User.search(params[:search]).order("created_at DESC")
    else
      @users = User.all.order('created_at DESC')
    end
  end	

  def searchcontent
    begin
	  @search = params[:search]
	  page     = Search::Timeline.new(@search)
	  @timeline = page.construct(params)
    rescue
    end
	end

  def random_search
    getbeginning = ['@', '#', '']
    choosefromlist = [
    'Wired', 
    'NatGeo', 
    'People', 
    'TIME', 
    'Sports Illustrated', 
    'Cosmopolitan', 
    'Redbull', 
    'ESPN', 
    'US Weekly', 
    'Entertainment', 
    'Newsweek', 
    'PopSci', 
    'Vogue', 
    'Bloomberg', 
    'GQ Magazine', 
    'HGTV', 
    'Forbes', 
    'Fortune', 
    'E! News', 
    'Google', 
    'TED Talks', 
    'Tesla', 
    "Victoria's Secret", 
    'CNN', 
    'HBO', 
    'Showtime', 
    'Marvel', 
    'Syfy', 
    'Netflix', 
    'Buzzfeed', 
    'Reddit', 
    'CollegeH umor', 
    'Microsoft', 
    'Nike', 
    'IMDb', 
    'Vevo', 
    'Star Wars', 
    'NASA', 
    'Bravo', 
    'MTV', 
    'Golf Digest', 
    'NBA', 
    'NFL', 
    'MLB', 
    'NHL', 
    'Inc', 
    'Makerbot', 
    'Olympics', 
    'TMZ', 
    'Tiffany & Co', 
    'Playboy', 
    'Maxim', 
    'ELLE', 
    'Vanity Fair', 
    'Brides', 
    'USA TODAY', 
    'Science Channel', 
    'FIFA', 
    'Gucci', 
    'H & M', 
    'General Electric', 
    'Armani', 
    'IBM', 
    'FOX Sports', 
    'CNBC', 
    'Amazon', 
    'Food Network', 
    'Sony', 
    'Gap', 
    'History', 
    'Ralph Lauren', 
    'TLC', 
    'Xbox', 
    'PlayStation', 
    'Nordstrom', 
    'Entrepreneur', 
    'Banana Republic', 
    'Calvin Klein', 
    'Under Armour', 
    'Facebook', 
    'Burberry', 
    'ABC', 
    'NBC', 
    'CBS', 
    'The CW', 
    'Hugo Boss', 
    'CBS News', 
    'Fox News', 
    'NBC News', 
    'ABC News', 
    'CBS Sports', 
    'FOX', 
    'Uber', 
    'Forever 21', 
    'MLS', 
    'Urban Outfitters', 
    'Allure', 
    'W Magazine', 
    'The Scene', 
    'YouTube', 
    'Katy Perry', 
    'Barack Obama', 
    'Taylor Swift', 
    'Lady Gaga', 
    'Justin Timberlake', 
    'Britney Spears', 
    'Kim Kardashian', 
    'Shakira', 
    'Jennifer Lopez', 
    'Selena Gomez', 
    'Ariana Grande', 
    'Demi Lovato', 
    'Jimmy Fallon', 
    'LeBron James', 
    'Adele', 
    'Bruno Mars', 
    'Alicia Keys', 
    'Miley Cyrus', 
    'Nicki Minaj', 
    'Emma Watson', 
    'Neil Patrick Harris', 
    'David Guetta', 
    'Conan OBrien', 
    'Khloe Kardashian', 
    'Kourtney Kardashian', 
    'Christina Aguilera', 
    'Beyonce', 
    'Oprah Winfrey', 
    'Johnny Depp', 
    'Scarlett Johansson', 
    'Madonna', 
    'Tom Hanks', 
    'Jessica Alba', 
    'Megan Fox', 
    'Tiger Woods', 
    'Blake Lively', 
    'Leonardo DiCaprio', 
    'Emma Stone', 
    'jay Z', 
    'Ellen DeGeneres', 
    'Sandra Bullock', 
    'Ashley Greene', 
    'Natalie Portman', 
    'Jennifer Lawrence', 
    'Kate Bosworth', 
    'Cameron Diaz', 
    'Milla Kunis', 
    'Floyd Mayweather', 
    'Reese Witherspoon', 
    'Kate Upton', 
    'Peter Dinklage', 
    'Armani', 
    'Burberry', 
    'Calvin Klein', 
    'CHANEL', 
    'Dior', 
    'Christian Louboutin', 
    'Dolce and Gabbana', 
    'DKNY', 
    'ESCADA', 
    'Fendi', 
    'Gucci', 
    'Prada', 
    'HUGO BOSS', 
    'John Varvatos', 
    'La Perla Lingerie', 
    'Louis Vuitton', 
    'Manolo Blahnik', 
    'Missoni', 
    'Ralph Lauren', 
    'Roland Mouret', 
    'Stella McCartney', 
    'TOM FORD', 
    'Versace', 
    'Michael Kors', 
    'All Recipes', 
    'Cooking.com', 
    'Food Network', 
    'The Kitchn', 
    'Open Table', 
    'Taste Of Home', 
    'Epicurious', 
    'Grub Hub', 
    'Seamless', 
    'Yummly', 
    'Huffington Post Food', 
    'Food.com', 
    'BonAppetit.com', 
    'Weight Watchers', 
    'Food And Wine', 
    'The Chew', 
    'Americas Test Kitchen', 
    'Iron Chef America', 
    'One Direction', 
    'Katy Perry', 
    'Beyonce', 
    'Taylor Swift', 
    'Justin Timberlake', 
    'Iggy Azalea', 
    'Ariana Grande', 
    'Miley Cyrus', 
    'Pharrell Williams', 
    'Eminem', 
    'Lorde', 
    'Luke Bryan', 
    'Sam Smith', 
    'John Legend', 
    'One Republic', 
    'Drake', 
    'Jason Derulo', 
    'Justin Bieber', 
    'Imagine Dragons', 
    'Florida Georgia Line', 
    'Nicki Minaj', 
    '5 Seconds of Summer', 
    'Lady Gaga', 
    'Pitbull', 
    'Bruno Mars', 
    'Jason Aldean', 
    'Maroon 5', 
    'Chris Brown', 
    'Meghan Trainor', 
    'Bastille', 
    'Avicii', 
    'Magic!', 
    'Demi Lovato', 
    'Blake Shelton', 
    'Coldplay', 
    'Charli XCX', 
    'Nico & Vinz', 
    'The Rolling Stones', 
    'Shakira', 
    'Passenger', 
    'Brantley Gilbert', 
    'Ellie Goulding', 
    'Eric Church', 
    'Idina Menzel', 
    'Selena Gomez', 
    'Calvin Harris', 
    'Michael Buble', 
    'Michael Jackson', 
    'Britney Spears', 
    'Kelly Clarkson', 
    'Christinaa Guilera', 
    'Real Madrid', 
    'Dallas Cowboys', 
    'New York Yankees', 
    'Barcelona', 
    'Manchester United', 
    'Los Angeles Lakers', 
    'New England Patriots', 
    'New York KNicks', 
    'Los Angeles Dodgers', 
    'Washington Redskins', 
    'Bayern Munich', 
    'Boston Red Sox', 
    'New York Giants', 
    'Chicago Bulls', 
    'San Francisco Giants', 
    'Houston Texans', 
    'Chicago Cubs', 
    'New York Jets', 
    'Philadelphia Eagles', 
    'Boston Celtics', 
    'Chicago Bears', 
    'Los Angeles Clippers', 
    'San Francisco 49ers', 
    'Baltimore Ravens', 
    'Brooklyn Nets', 
    'Denver Broncos', 
    'Indianapolis Colts', 
    'St. Louis Cardinals', 
    'Greenbay Packers', 
    'Manchester City', 
    'Chelsea', 
    'Ferrari', 
    'New York Mets', 
    'Pittsburgh Steelers', 
    'Seattle Seahawks', 
    'Arsenal', 
    'Golden State Warriors', 
    'Angels of Anaheim', 
    'Miami Dolphins', 
    'Toronto Maple Leafs', 
    'Washington Nationals', 
    'Carolina Panthers', 
    'Houston Rockets', 
    'Philadelphia Phillies', 
    'Tampa Bay Buccaneers', 
    'Texas Rangers', 
    'Miami Heat', 
    'Tennessee Titans', 
    'Atlanta Braves', 
    'Minnesota Vikings', 
    'Arizona Cardinals', 
    'Drew Binsky', 
    'Budget Travel', 
    'Afar', 
    'Travel and Leisure', 
    'Condenast Traveler', 
    'Geographical', 
    'NatGeo', 
    'Wanderlust', 
    'Last Week Tonight', 
    'Game Of Thrones', 
    'BetterCallSaul', 
    'Orange Is The New Black', 
    'Empir', 
    'HIMYM', 
    'Mad Men', 
    'The Americans', 
    'THe Tonight Show', 
    'True Detective', 
    'Justified', 
    'Sense8', 
    'iZombie', 
    'The Flash', 
    'The Bachelor', 
    'Suits', 
    'The Ellen Show', 
    'Greys Annotomy', 
    'The Walking Dead', 
    'American Horror Story', 
    'Shark Tank', 
    'Gotham', 
    'The Good Wife', 
    'The Big Bang Theory', 
    'Blacklist', 
    'How To Get Away With Murder', 
    'The Voice', 
    'Bachelorette', 
    'Scandal', 
    'Downton Abbey', 
    'Dancing With the Stars', 
    'AmericanIdol', 
    'Mentalist', 
    'House of Cards', 
    'Transparent', 
    'Louie', 
    'Community', 
    'Parks and Recreation', 
    'Sons of Anarchy', 
    'Brooklyn 99', 
    'Jane The Virgin', 
    'Fargo', 
    'Saturday Night Live', 
    'Mr. Robot', 
    'New Girl', 
    'Scorpion', 
    'Modern Family', 
    'The Mindy Project', 
    'Tyler Oakley', 
    'Troye Sivan', 
    'Zoella', 
    'Connor Franta', 
    'I Justine', 
    'GloZell', 
    'Jenna Marbles', 
    'Alfie Deyes', 
    'Shane Dawson', 
    'Joey Graceffa', 
    'Rebecca Black', 
    'PewDiePie', 
    'Smosh', 
    'Niga Higa', 
    'Tobuscus', 
    'Sawyer Hartman', 
    'Annoying Orange', 
    'Rhett and Link', 
    'ItsKingsleyBitch', 
    'Jim Chapman', 
    'Dan Is Not On Fire', 
    'KickThePj', 
    'Catrific', 
    'Tay Zonday', 
    'Marcus Butler', 
    'Benjamin Cook', 
    'Olga Kay', 
    'Hannah Hart', 
    'Anthony Padilla', 
    'Julian Smith', 
    'Amazing Phil', 
    'Sam Pepper', 
    ]
    @searched = getbeginning.shuffle.first + choosefromlist.shuffle.first
    page     = Search::Timeline.new(@searched)
    @timeline = page.construct(params)
  end
end